packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.56.2
  "@trpc/client": ^11.0.0-rc.580
  "@trpc/react-query": ^11.0.0-rc.580
  "@trpc/server": ^11.0.0-rc.580
  tailwindcss: ^3.4.13
  typescript: ^5.6.3
catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
